config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  scope :ordered, -> { order(id: :desc) }
  validates :title, :body, presence: true

  broadcasts_to -> (post) { "posts" }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.ordered
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.turbo_stream
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostsTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for post, html: { class: 'form post'} do |form| %>
  <% if post.errors.any? %>
    <div style="color: red;flex-basis: 100%">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :title, input_html: {autofocus: true} %>
  <%= form.input :body %>
  <%= link_to "Cancel", posts_path, class: "btn btn--light" %>

  <%= form.submit class: "btn btn--primary" %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post do %>
  <div class="post">
      <%= link_to post.title, post_path(post), data: {turbo_frame: "_top"} %>

      <%= post.body %>

      <div class="post__actions">
        <%= button_to "Delete", post_path(post), method: :delete, data: {turbo_frame: "_top"}, class: "btn btn--light" %>
        <%= link_to "Edit", edit_post_path(post), class: "btn btn--light" %>
      </div>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", partial: "posts/post", locals: { post: @post } %>
<%= turbo_stream.update Post.new, "" %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<main class="container">
  <div class="header">
    <%= link_to "Back to posts", posts_path, class: "btn btn--primary" %>
  </div>

  <%= turbo_frame_tag @post do %>
    <%= render "form", post: @post %>
  <% end %>
</main>

app/views/posts/index.html.erb
<%= turbo_stream_from "posts" %>

<main class="container">
  <p style="color: green"><%= notice %></p>

  <div class="header">
    <h1>Posts</h1>
    <%= link_to "New post", new_post_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Post.new) } %>
  </div>

  <%= turbo_frame_tag Post.new %>

  <%= turbo_frame_tag "posts" do %>
    <%= render @posts %>
  <% end %>
</main>

app/views/posts/new.html.erb
<main class="container">
  <%= link_to "Back", posts_path %>

  <div class="header">
    <h1>New post</h1>
  </div>

  <%= turbo_frame_tag @post do %>
    <%= render "form", post: @post %>
  <% end %>
</main>

app/views/posts/show.html.erb
<main class="container">
  <div class="header">
    <%= link_to "Back to posts", posts_path, class: "btn btn--primary" %>
  </div>

  <%= render @post %>
</main>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.update @post, @post %>